export const ANIME_FETCHING = 'ANIME_FETCHING';
export const ANIME_FETCHED = 'ANIME_FETCHED';
export const ANIME_FETCHED_ERROR = 'ANIME_FETCHED_ERROR';
export const DETAILS_FETCHING = 'DETAILS_FETCHING';
export const DETAILS_FETCHED = 'DETAILS_FETCHED';
export const DETAILS_FETCHED_ERROR = 'DETAILS_FETCHED_ERROR';